### ISSUE TITLE
Page imports are not working properly

### ISSUE THREAD

**Issue by sansyrox** [sparckles/starfyre#84]
https://github.com/sparckles/starfyre/blob/bb0c0b895fb6fb9314b541afb6ee05bcdd1098a5/test-application/pages/__init__.fyre#L1-L2

It is magically able to resolve these imports.

They should be organised either

```
from ..parent import parent

```
or 

```
from test_application.parent import parent
```

**Comment by DeleMike** [comment]
Hello @sansyrox, I have been looking at this issue and I have discovered why it always resolves the imports regardless of how it is structured is because when we compile the fyre files to generate all the IR files(Python files), we compile all the fyre files in the application to be stored in the `pages` directory.

What do I mean?
So we have the `pages` directory, and inside it, we have (`home.fyre` and `about.fyre`). Outside pages, we have `parent.fyre` and `store.fyre`.
During the compilation of the starfyre project, all the fyre files that are transpiled are stored in the build/pages folder except the `__init__.py` and `__main__.py`.

I believe that we should first resolve the imports if they are valid before we proceed with the compilation, this is correct, right?
So this issue is to make sure the user writes a valid import statement when trying to import fyre files into other pages?
